name: nessus-manager-prod

releases:
- name: nessus-manager
  version: latest
- name: cron
  version: latest

networks:
  - name: tooling
    type: manual
    subnets:
      - range: (( grab meta.network.range ))
        reserved: (( grab meta.network.reserved ))
        gateway: (( grab meta.network.gateway ))
        dns: (( grab meta.network.dns ))
        static:
        - (( grab meta.network.static ))
        cloud_properties:
          security_groups: (( grab meta.network.security_groups ))
          subnet: (( grab meta.network.subnet ))

jobs:
- name: nessus-manager
  templates:
  - {name: nessus-manager, release: nessus-manager}
  - {name: cron, release: cron}
  instances: 1
  resource_pool: t2.medium
  persistent_disk_pool: nessus-manager
  networks:
  - name: tooling
    static_ips: (( static_ips(1) ))

properties:
  env: nessus-manager
  cron:
    entries:
    - command: /var/vcap/jobs/nessus-manager/bin/health.sh
      minute: '*/5'
      hour: '*'
      day: '*'
      month: '*'
      wday: '*'
      user: root
  nessus-manager:
    license: (( grab meta.nessus-manager.license ))
    username: (( grab meta.nessus-manager.username ))
    password: (( grab meta.nessus-manager.password ))

resource_pools:
- name: t2.medium
  network: tooling
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.medium
    elbs: (( grab meta.elbs ))
    ephemeral_disk:
      size: 30000
      type: gp2
      encrypted: true
    availability_zone: (( grab meta.az ))

disk_pools:
- name: nessus-manager
  disk_size: 60000
  cloud_properties:
    encrypted: true

compilation:
  network: tooling
  reuse_compilation_vms: true
  workers: 2
  cloud_properties:
    instance_type: t2.medium
    iam_instance_profile: (( grab terraform_outputs.bosh_compilation_profile ))
    ephemeral_disk:
      size: 30000
      type: gp2
      encrypted: true
    availability_zone: (( grab meta.az ))

update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-300000
