---
name: nessus-manager-prod

director_uuid: (( param "specify director uuid" ))

releases:
- name: nessus-manager
  version: latest
- name: cron
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-300000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-300000

stemcell:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: nessus-manager
  stemcell: default
  networks:
  - name: nessus-manager
    static_ips:
    - (( grab terraform_outputs.nessus_static_ip ))
 jobs:
      - name: nessus-manager
        release: nessus-manager
        properties:
          nessus-manager:
            license: (( grab meta.nessus-manager.license ))
            username: (( grab meta.nessus-manager.username ))
            password: (( grab meta.nessus-manager.password ))
      - name: cron
        release: cron
        properties:
          cron:
            entries:
            - command: /var/vcap/jobs/nessus-manager/bin/health.sh
              minute: '*/5'
              hour: '*'
              day: '*'
              month: '*'
              wday: '*'
              user: root

  azs: [z1]
  vm_type: nessus-manager
  vm_extensions: [nessus-manager-lb]
  instances: 1
  persistent_disk_type: nessus-manager
